<?php

/**
* Implementation of hook_shortcode_info().
* Using same formatting as hook_filter_info()
*/
function shortcode_basic_tags_shortcode_info() {
  $shortcodes['quote'] = array(
    'title' => t('Quote'), 
    'description' => t('Replace a given text formatted like a quote.'), 
    'process callback' => 'shortcode_basic_tags_shortcode_quote', 
    //'settings callback' => '_shortcode_settings_form', TODO
    'attributes callback' => "shortcode_basic_tags_quote_attributes",
    'tips callback' => 'shortcode_basic_tags_shortcode_quote_tip',
    'default settings' => array(),
  );
  $shortcodes['img'] = array(
    'title' => t('Image'), 
    'description' => t('Show a image.'), 
    'process callback' => 'shortcode_basic_tags_shortcode_img', 
    //'settings callback' => '_shortcode_settings_form', TODO
    'tips callback' => 'shortcode_basic_tags_shortcode_img_tip',
    'default settings' => array(),
  );
  $shortcodes['highlight'] = array(
    'title' => t('Highlight'), 
    'description' => t('Insert a span around the text with highlight css class.'), 
    'process callback' => 'shortcode_basic_tags_shortcode_highlight', 
    //'settings callback' => '_shortcode_settings_form', TODO
    'tips callback' => 'shortcode_basic_tags_shortcode_highlight_tip',
    'default settings' => array(),
  );
    $shortcodes['button'] = array(
    'title' => t('Button'), 
    'description' => t('Insert a link formatted like a button.'), 
    'process callback' => 'shortcode_basic_tags_shortcode_button', 
    //'settings callback' => '_shortcode_settings_form', TODO
    'tips callback' => 'shortcode_basic_tags_shortcode_button_tip',
    'default settings' => array(),
  );
  $shortcodes['dropcap'] = array(
    'title' => t('Dropcap'), 
    'description' => t('Replace a given text formatted like a dropcap.'), 
    'process callback' => 'shortcode_basic_tags_shortcode_dropcap', 
    //'settings callback' => '_shortcode_settings_form', TODO
    'tips callback' => 'shortcode_basic_tags_shortcode_dropcap_tip',
    'default settings' => array(),
  );
  $shortcodes['item'] = array(
    'title' => t('Item'), 
    'description' => t('Insert div or span around the text with some css classes.'), 
    'process callback' => 'shortcode_basic_tags_shortcode_item', 
    //'settings callback' => '_shortcode_settings_form', TODO
    'tips callback' => 'shortcode_basic_tags_shortcode_item_tip',
    'default settings' => array(),
  );
  $shortcodes['clear'] = array(
    'title' => t('Clear'), 
    'description' => t('Insert a clearer div for a proper layout.'), 
    'process callback' => 'shortcode_basic_tags_shortcode_clear', 
    //'settings callback' => '_shortcode_settings_form', TODO
    'tips callback' => 'shortcode_basic_tags_shortcode_clear_tip',
    'default settings' => array(),
  );
  $shortcodes['link'] = array(
    'title' => t('Link'), 
    'description' => t('Makes an aliased link to the given path.'), 
    'process callback' => 'shortcode_basic_tags_shortcode_link',
    //'settings callback' => '_shortcode_settings_form', TODO
    'tips callback' => 'shortcode_basic_tags_shortcode_link_tip',
    'default settings' => array(),
  );
  
  return $shortcodes;
}

/**
* Implementation of hook_theme().
*/
function shortcode_basic_tags_theme() {
  return array(
    'shortcode_button' => array(
      'variables' => array('link' => '#', 'text' => '', 'class' => 'button'),
    ),
    'shortcode_quote' => array(
      'variables' => array('text' => '', 'author' => FALSE, 'class' => 'quote'),
    ),
    'shortcode_img' => array(
      'variables' => array('src' => '', 'alt' => '', 'class' => 'img'),
    ),
    'shortcode_dropcap' => array(
      'variables' => array('text' => '', 'class' => 'dropcap'),
    ),
    'shortcode_item' => array(
      'variables' => array('text' => '', 'id' => '', 'class' => '', 'type' => 'div'),
    ),
    'shortcode_clear' => array(
      'variables' => array('text' => '', 'id' => '', 'class' => '', 'type' => 'div'),
    ),
  );
}

/**
 * Insert a span around the text with highlight css class
 *
 * Calling
 * [highlight]text[/highlight]
 *
 *
 * If the length empty or invalid, between 1-99, the length will be 8
 *
 */
function shortcode_basic_tags_shortcode_highlight($attrs, $text) {
  extract( shortcode_attrs( array(
      'class'  => '',
      ), $attrs ));

  $class = shortcode_add_class($class, 'highlight');
  return '<span class="' . $class . '">' . $text . '</span>';
}

function shortcode_basic_tags_shortcode_highlight_tip($format, $long) {
  $output = '<p><strong>[highlight (class="additional class")]text[/highlight]</strong>';
  if ($long) {
    $output .= ' insert a span.highlight around the text.</p>';
    $output .= '<p>Sample css:</p>';
    $output .= '
      <code>
        span.highlight{
        background-color:red;
        }
        span.highlight2{
        background-color:cyan;
        }
      </code><p>&nbsp</p>';
  }
  else {
    $output .= ' insert a span.highlight around the text. Additional class names can be added by the <em>class</em> parameter.</p>';
  }

  return $output;
}

function shortcode_basic_tags_shortcode_button($attrs, $text) {
  extract(shortcode_attrs( array(
      'title' => 'title default',
      'class' => 'button',
      'url' =>  '',
      'path' =>  '/',
      // ...etc
      ), $attrs ));

  $class = shortcode_add_class($class, 'button');

  if ($url) {
   $path = $url;
  }
  $path = url($path);
  return theme('shortcode_button', array('path' => $path, 'text' => $text, 'class' => $class));
}

function shortcode_basic_tags_shortcode_button_tip($format, $long) {
  $output = '<p><strong>[button path="path" (class="additional class")]text[/button]</strong>';
  if ($long) {
    $output .= ' insert a link formatted like a button. Use url parameter for the link.</p>';
  }
  else {
    $output .= ' insert a link formatted like a button. The <em>url</em> parameter provides the link target. The <em>title</em> will be formatted as a link title (small tooltip over the link - helps for SEO). Additional class names can be added by the <em>class</em> parameter.</p>';
  }


  return $output;
}

function theme_shortcode_button($vars) {
  return '<a href="' . $vars['path'] . '" class="' . $vars['class'] . '"><span>' . $vars['text'] . '</span></a>';
}


function shortcode_basic_tags_shortcode_dropcap($attrs, $text) {
  extract(shortcode_attrs( array(
      'class' => 'dropcap',
      // ...etc
      ), $attrs ));

  $class = shortcode_add_class($class, 'dropcap');
  return theme('shortcode_dropcap', array('text' => $text, 'class' => $class));
}

/**
 * Theme hook for dropcap
 * @param $text
 * @param $class
 */
function theme_shortcode_dropcap($vars) {
  return '<span class="' . $vars['class'] . '">' . $vars['text'] . '</span>';
}

function shortcode_basic_tags_shortcode_dropcap_tip($format, $long) {
  $output = '<p><strong>[dropcap (class="additional class")]text[/dropcap]</strong>';
  if ($long) {
    $output .= ' replace a given text formatted like a dropcap.</p>';
    $output .= '<p>Sample css:</p>';
    $output .= '<code>
    .dropcap {
      display:block;
      float:left;
      font-size:38px;
      line-height:38px;
      vertical-align:baseline;
      padding-right:5px;
    }
    </code><p>&nbsp</p>';

  }
  else {
    $output .= ' replace a given text formatted like a dropcap. Additional class names can be added by the <em>class</em> parameter.</p>';
  }

  return $output;
}

function shortcode_basic_tags_quote_attributes($form, &$form_state) {
  $form['class'] = array(
    '#title' => t('class'), 
    '#type' => 'textfield', 
  );
    
  return $form;
}

function shortcode_basic_tags_quote_options_submit($form, &$form_state) {
}

/**
 *
 * Replace a given text formatted like a quote.
 * @param $attrs
 * @param $text
 */
function shortcode_basic_tags_shortcode_quote($attrs, $text) {
  extract(shortcode_attrs(array(
      'class' => 'quote',
      'author' => '',
      ), $attrs));

  $class = shortcode_add_class($class, 'quote');

  return theme('shortcode_quote', array('text' => $text, 'author' => $author, 'class' => $class));
}

function theme_shortcode_quote($vars) {
  $output = '';

  if(!empty($vars['author'])) {
    // Add author
    $output = '<span class="quote-author">'. t('%name wrote:', array('%name' => $vars['author'])) .'</span>';
  }
  $output .= $vars['text'];

  return '<span class="' . $vars['class'] . '">' . $output . '</span>';
}

function shortcode_basic_tags_shortcode_quote_tip($format, $long) {
  $output = '<p><strong>[quote (class="additional class" | author="author name")]text[/quote]</strong>';
    if ($long) {
      $output .= ' replace a given text formatted like a quote.</p>';
      $output .= '<p>Sample css:</p>';
      $output .= '<code>
        .quote {
           display:block;
           float:left;
           width:30%;
           margin:20px;
           margin-left:0;
           padding:5px 0 5px 20px;
           font-style:italic;
           border-left:3px solid #E8E8E8;
           line-heigh:1.5em;
           font-size:14px;
           letter-spacing: 1px;
           word-spacing: 2px;
        }

        .quote.right{
          float:right;
          margin-right:0;
          margin-left:20px;
        }
        </code><p>&nbsp</p>';
    }
    else {
      $output .= ' replace a given text formatted like a quote. Additional class names can be added by the <em>class</em> parameter.</p>';
    }

  return $output;
}

function shortcode_basic_tags_shortcode_img($attrs, $text) {
  extract(shortcode_attrs(array(
      'class' => 'img',
      'alt' => '',
      ), $attrs));

  $class = shortcode_add_class($class, 'img');

  return theme('shortcode_img', array('src' => $text, 'alt' => $alt, 'class' => $class));
}

function theme_shortcode_img($vars) {
  //$alt = (!empty($vars['alt'])) ? ' alt="'. $vars['alt'] .'" ' : '';
  
  return '<img src="'. url($vars['src']) .'" class="' . $vars['class'] . '" alt="' . $alt . '"/>';
}

function shortcode_basic_tags_shortcode_img_tip($format, $long) {
  $output = '<p><strong>[img (class="additional class" | alt="alt text")]image url[/img]</strong>';
  $output .= ' inserts a image based on the given url.</p>';

  return $output;
}

function shortcode_basic_tags_shortcode_item($attrs, $text) {
  extract(shortcode_attrs( array(
      'class' => '',
      'style' => '',
      'id' => '',
      'type' => 'div',
      // ...etc
      ), $attrs ));

  switch ($type) {
    case 's':
    case 'span':
      $type = 'span';
    break;

    default:
      $type = 'div';
    break;
  }

  return theme('shortcode_item', array('text' => $text, 'id' => $id, 'class' => $class, 'type' => $type, 'style' => $style));
}

function shortcode_basic_tags_shortcode_item_tip($format, $long) {
  $output = '<p><strong>[item (class="additional class"|id=item id|type=div,d,span,s)]text[/item]</strong>';
  if ($long) {
    $output .= ' Insert a html item (type parameter = div or span) around the given text.</p>';
    $output .= '<p>Additional class names can be added by the <em>class</em> parameter. Id parameter gives the html an unique css id.</p>';
    $output .= '<p>&nbsp</p>';
  }
  else {
    $output .= ' Insert a html item (div or span) around the given text.</p>';
  }

  return $output;
}

function theme_shortcode_item($vars) {
  $id = empty($vars['id']) ? '' : ' id="' . $vars['id'] . '"';
  $class = empty($vars['class']) ? '' : ' class="' . $vars['class'] . '"';
  $style = empty($vars['style']) ? '' : ' style="' . $vars['style'] . '"';

  return '<' . $vars['type'] . $id . $class . $style . '>' . $vars['text'] . '</' . $vars['type'] . '>';
}

function shortcode_basic_tags_shortcode_clear($attrs, $text) {
  extract(shortcode_attrs( array(
      'class' => '',
      'style' => '',
      'id' => '',
      'type' => 'div',
      // ...etc
      ), $attrs ));

  $class = shortcode_add_class($class, 'clear-block');

  switch ($type) {
    case 's':
    case 'span':
      $type = 'span';
    break;

    default:
      $type = 'div';
    break;
  }

  return theme('shortcode_clear', array('text' => $text, 'id' => $id, 'class' => $class, 'type' => $type, 'style' => $style));
}

// TODO: fill it
function shortcode_basic_tags_shortcode_clear_tip($format, $long) {
  $output = '<p><strong>[clear (class="additional class"|id=item id|type=div,d,span,s)]text[/clear]</strong>';
  if ($long) {
    $output .= ' Insert a html item (type parameter = div or span) around the given text.</p>';
    $output .= '<p>Additional class names can be added by the <em>class</em> parameter. Id parameter gives the html an unique css id.</p>';
    $output .= '<p>&nbsp</p>';
  }
  else {
    $output .= ' Insert a html item (div or span) around the given text.</p>';
  }

  return $output;
}

function theme_shortcode_clear($vars) {
  $id = empty($vars['id']) ? '' : ' id="' . $vars['id'] . '"';
  $class = empty($vars['class']) ? '' : ' class="' . $vars['class'] . '"';
  $style = empty($vars['style']) ? '' : ' style="' . $vars['style'] . '"';

  return '<' . $vars['type'] . $id . $class . $style . '>' . $vars['text'] . '</' . $vars['type'] . '>';
}

/*
 * Create aliased link
 *
 * param $text = the linked text
 * attr[path] = the path we need aliaded
 *
 */
function shortcode_basic_tags_shortcode_link($attrs, $text) {
  extract(shortcode_attrs( array(
      'path' => '<front>',
      'title' => '',
      // ...etc
      ), $attrs ));

  $path = url($path);
  if ($text) {
    $class = empty($class) ? '' : ' class="' . $class . '"';
    $style = empty($style) ? '' : ' style="' . $style . '"';
    $id = empty($id) ? '' : ' id="' . $id . '"';
    if ($title == '<none>') {
      $title = '';
    }
    else {
      $title = empty($title) ? check_plain($text) : check_plain($title);
      $title = ' title="' . $title . '"';
    }
    return '<a href="' . $path . '"' . $id . $class . $style . $title . '>' . $text . '</a>';
  }
  return $path;
}

function shortcode_basic_tags_shortcode_link_tip($format, $long) {
  $output = '<p><strong>[link path="the drupal path" (title="link title"|class="additional class"|id=item id|style=css style rules)]text[/link]</strong>';
  if ($long) {
    $output .= ' inserts an aliased drupal path around the text. You can omit the text and the closing [/link], you gives back the url only.</p>';
    $output .= '<p>Additional class names can be added by the <em>class</em> parameter. Id parameter gives the html an unique css id. In the <em>style</em> parameter you can use a css definitions.</p>';
    $output .= '<p>&nbsp</p>';
  }
  else {
    $output .= ' inserts an aliased drupal path around the text. You can omit the text and the closing [/link], you gives back the url only.</p>';
  }

  return $output;
}
